"""add new column status in todo table

Revision ID: c57428fe3fd5
Revises: 379cb29e57ce
Create Date: 2026-02-14 17:22:37.166935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57428fe3fd5'
down_revision: Union[str, Sequence[str], None] = '379cb29e57ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
